name: Sync Terraform Modules
run-name: sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      force:
        description: 'Force sync everything'
        required: false
        default: 'false'
        type: choice
        options:
        - true
        - false

jobs:
  sync-readmes-from-modules:
    name: Sync ${{ matrix.modules.cloudid }} modules
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # treat each job as separate
      max-parallel: 1 # prevent conflicts with git commit
      matrix:
        modules:
          - cloudid: aws
            repo: 'terraform-aws-vmseries-modules'
          - cloudid: azure
            repo: 'terraform-azurerm-vmseries-modules'
          - cloudid: gcp
            repo: 'terraform-google-vmseries-modules'
    steps:
      - name: Checkout module repo for ${{ matrix.modules.cloudid }}
        uses: actions/checkout@v3
        with:
          repository: PaloAltoNetworks/${{ matrix.modules.repo }}
          path: ${{ matrix.modules.repo }}
          ref: readme-updates-for-automation-hub

      - name: Check if commit to repo today
        if: github.event.inputs.force != 'true'
        id: check_commit
        run: |
          cd ${{ matrix.modules.repo }}
          git log --since="1 day ago" --pretty=format:"%h" | grep -q . && echo "changes=true" || echo "changes=false" >> "$GITHUB_OUTPUT"
      
      - name: No changes found
        if: steps.check_commit.outputs.changes == 'false'
        run: |
          echo "::notice ::No changes found in ${{ matrix.modules.repo }} on $(date -u)" 

      - name: Checkout local scripts
        if: steps.check_commit.outputs.changes != 'false'
        uses: actions/checkout@v3
        with:
          path: 'scripts'

      - name: Checkout output branch
        if: steps.check_commit.outputs.changes != 'false'
        uses: actions/checkout@v3
        with:
          ref: 'output'
          path: 'output'

      - name: Setup Python
        if: steps.check_commit.outputs.changes != 'false'
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies

      - name: Install Python Dependencies
        if: steps.check_commit.outputs.changes != 'false'
        run: |
          python -m pip install --upgrade pip
          pip install -r ./scripts/requirements.txt

      - name: Sync module readmes to pan.dev
        if: steps.check_commit.outputs.changes != 'false'
        run: |
          tree .
          python ./scripts/process_modules_readmes.py "./${{ matrix.modules.repo }}/modules" "./output/${{ matrix.modules.cloudid }}/vmseries/modules"
          python ./scripts/process_modules_readmes.py --type refarch "./${{ matrix.modules.repo }}/examples" "./output/${{ matrix.modules.cloudid }}/vmseries/reference-architectures"
      
      - name: Commit and push changes
        if: steps.check_commit.outputs.changes != 'false'
        run: |
          tree "./output"
          cd output
          git config --global user.name 'GitHub Actions'
          git config --global user.email '<>'
          git add -A
          git status
          git commit -m "Sync module readmes for ${{ matrix.modules.cloudid }} on $(date -u)"
          git push origin output
