name: Sync Terraform Modules
run-name: sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync-readmes-from-modules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          [
            'PaloAltoNetworks/terraform-aws-vmseries-modules',
            'PaloAltoNetworks/terraform-azurerm-vmseries-modules',
            'PaloAltoNetworks/terraform-google-vmseries-modules',
          ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.repo }}
          path: ${{ matrix.repo }}
          fetch-depth: 1

      - name: Check if commit to repo today
        id: check_commit
        run: |
          cd ${{ matrix.repo }}
          git log --since="1 day ago" --pretty=format:"%h" | grep -q .

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pip' # caching pip dependencies

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync module readmes to pan.dev
        run: |
          mkdir ./output
          python process_modules_readmes.py "${{ matrix.repo }}/modules" "./output"
